### ISSUE TITLE
Deploy Data Portal to cgl-dev with CGL Dev GitLab instance.

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#698]
I was able to login to:

https://gitlab.dev.REDACTED/

With my github credentials, and import the https://github.com/HumanCellAtlas/data-portal repo however I can not seem to create a "pull" mirroring repository.

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/589d2de3-0c70-496e-aa99-363cc84f2b12)

I was gong to add a key pair to see if that helped, but I felt I should not be adding key pairs on behalf of the CGL, and felt these may be centrally managed.

I seem to be in a "Clever Canary" group that I am a maintainer of which is great but was wondering if this is somehow restricting my permissions to create a mirroring repo. 

The permissions I will need are to write to a specific bucket and to invalidate a specific cloud-front cache, one per lower environment 

@hannes-ucsc am I heading in the right direction here? In general how do you think I should proceed?

Cheers and Thanks,
D

**Comment by hannes-ucsc** [comment]
We don't use mirroring because last time I checked it was an enterprise edition feature, but more importantly, because it poses a security risk in my opinion.

We handle this in Azul by explicitly pushing to the repo and this has worked well for us.

Cheers and you're welcome.

**Comment by NoopDog** [comment]
Thanks, this will work just fine.

**Comment by hannes-ucsc** [comment]
Great!

**Comment by NoopDog** [comment]
OK then! Off to the permissions part. Build completing ok, but when we try to deploy we get Access Denied errors.

```
$ export BUCKET=s3://dev.singlecell.gi.ucsc.edu/
 $ if [ "$MAINTENANCE" = "true" ];then export SRCDIR=maintenance/; else export SRCDIR=public/; fi
 $ aws s3 sync --acl public-read $SRCDIR $BUCKET --delete
 delete failed: s3://dev.singlecell.gi.ucsc.edu/2a724fcd8b54b6301c35819d2a83b381/config.json An error occurred (AccessDenied) when calling the DeleteObject operation: Access Denied
````
We will also need to invalidate a cloud-front cache like:

```
- export BUCKET=s3://dev.singlecell.gi.ucsc.edu/
    - if [ "$MAINTENANCE" = "true" ];then export SRCDIR=maintenance/; else export SRCDIR=public/; fi
    - aws s3 sync --acl public-read $SRCDIR $BUCKET --delete
    - aws cloudfront create-invalidation --distribution-id E3562WJBOLN8W8 --paths "/*"
```

@hannes-ucsc what do we need to do so the deploy script can control the bucket and the cloudfront cache?

Cheers and Thanks, 
D

**Comment by hannes-ucsc** [comment]
You're welcome!!!

Please compile an [IAM policy document](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html#policies-introduction) listing the permissions that your build needs for a successful deployment and I will apply them to the Gitlab instance. These have to be fairly restrictive in both the operations they grant and the resources they apply to. So for example, you can't just request `s3:*` on every bucket and object. 

Please also let me know if your build is passing roles to other AWS entities like lambda functions or EC2 instances. If that's the case I need to extend the policy boundary as well.

**Comment by NoopDog** [comment]
@hannes-ucsc This should work. 
Let me know if you want me to actually create the policy or if you would prefer to do that.

Cheers,
Dave

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "VisualEditor0",
      "Effect": "Allow",
      "Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:ListBucket",
        "s3:DeleteObject"
      ],
      "Resource": [
        "arn:aws:s3:::dev.explore.singlecell.gi.ucsc.edu/*",
        "arn:aws:s3:::dev.singlecell.gi.ucsc.edu/*"
      ]
    },
    {
      "Sid": "VisualEditor1",
      "Effect": "Allow",
      "Action": "cloudfront:CreateInvalidation",
      "Resource": ["arn:aws:cloudfront::122796619775:distribution/E3562WJBOLN8W8"]
    }
  ]
}
```

**Comment by melainalegaspi** [comment]
Unassigned @hannes-ucsc bc his work is tracked by blocking ticket https://github.com/databiosphere/azul/issues/1893.

**Comment by hannes-ucsc** [comment]
The blocker has been resolved.

**Comment by NoopDog** [comment]
Awesome thanks, I will give it  a try.

**Comment by NoopDog** [comment]
Hi @hannes-ucsc. I tried this this morning. It seems it is still failing with access denied on the buckets.

0.4.8 python-dateutil-2.8.1 rsa-3.4.2 s3transfer-0.3.3 six-1.15.0 urllib3-1.25.9
 $ export BUCKET=s3://dev.singlecell.gi.ucsc.edu/
 $ if [ "$MAINTENANCE" = "true" ];then export SRCDIR=maintenance/; else export SRCDIR=public/; fi
 $ aws s3 sync --acl public-read $SRCDIR $BUCKET --delete
 delete failed: s3://dev.singlecell.gi.ucsc.edu/2a724fcd8b54b6301c35819d2a83b381/config.json An error occurred (AccessDenied) when calling the DeleteObject operation: Access Denied

https://gitlab.dev.singlecell.gi.ucsc.edu/clever-canary/data-portal/-/jobs/3828

**Comment by hannes-ucsc** [comment]
The policy you specified doesn't allow this operation. The resource ARNs are missing an asterisk in the right place. I didn't catch that either when I incorporated the policy. One of the ARNs is also invalid due to a duplicated string but I caught that problem and fixed it. I recommend that you edit the `azul-gitlab` policy manually via the AWS IAM console and retry the build until it passes. After you are sure that you got the policy right, let me know and I will make the change permanent.

**Comment by NoopDog** [comment]
Ah thanks @hannes-ucsc I have updated the policy above to add the /* to the buckets and also remove the duplicate  `arn:aws:s3`

I tried to modify this on AWS but it seems I do not have the required permissions (see the image below).

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/5f68ea2c-cbc2-4a61-b261-1322bf948a56)

Would you be able to either upgrade my permissions or add the /* to the two resource descriptors?  

Cheers and Thanks,
Dave

**Comment by hannes-ucsc** [comment]
You are welcome!

Try again now.

**Comment by hannes-ucsc** [comment]
On save, you may be asked to delete and older version. That's ok.

**Comment by NoopDog** [comment]
OK then,

Hi @hannes-ucsc 
This is working. 

The winning ACL is:

```
{
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:ListBucket",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::dev.singlecell.gi.ucsc.edu/*",
                "arn:aws:s3:::dev.explore.singlecell.gi.ucsc.edu/*",
                "arn:aws:s3:::dev.singlecell.gi.ucsc.edu",
                "arn:aws:s3:::dev.explore.singlecell.gi.ucsc.edu"
            ]
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": "cloudfront:CreateInvalidation",
            "Resource": "arn:aws:cloudfront::122796619775:distribution/E3562WJBOLN8W8"
        }
```

This is currently saved on the IAM policy just listing it here for posterity. 
Please go ahead and apply this policy permanently and I think we can close this.

Thanks!
D

**Comment by hannes-ucsc** [comment]
Okee, dokee, you are welcome!!!!!

Looks like the policy needed a few more changes …

The application of the policy will be tracked in the blocking ticket, so I'll unassign myself frmom this one.

**Comment by NoopDog** [comment]
Ok great, Yea I thought I coped it from one that was working. Well in any case it works now. Thanks for your help.

**Comment by hannes-ucsc** [comment]
You are welcome!!!!
